export interface BlogPost {
  slug: string;
  title: string;
  titleEn: string;
  excerpt: string;
  excerptEn: string;
  date: string;
  category: string;
  categoryEn: string;
  readTime: number;
  emoji: string;
  content: string[];
  contentEn: string[];
}

export const posts: BlogPost[] = [
  {
    slug: 'dian-te-esta-observando-facturacion-electronica',
    title: 'La DIAN Te Est\u00e1 Observando: Y S\u00ed, Sabe Cu\u00e1nto Gastaste en Almuerzo',
    titleEn: 'DIAN Is Watching You: And Yes, They Know How Much You Spent on Lunch',
    excerpt: 'Si cre\u00edas que pod\u00edas vender sin factura y vivir feliz, te tenemos noticias. La facturaci\u00f3n electr\u00f3nica lleg\u00f3 para quedarse, y tu excusa de "se me da\u00f1\u00f3 el sistema" ya no funciona.',
    excerptEn: 'If you thought you could sell without invoicing and live happily ever after, we have news. Electronic invoicing is here to stay, and your "the system crashed" excuse no longer works.',
    date: '2026-02-15',
    category: 'Facturaci\u00f3n',
    categoryEn: 'Invoicing',
    readTime: 5,
    emoji: '\uD83D\uDC41\uFE0F',
    content: [
      'Hab\u00eda una \u00e9poca dorada en Colombia donde pod\u00edas vender un mill\u00f3n de pesos en empanadas, recibir el dinero en efectivo, y la DIAN no ten\u00eda ni idea. Esos d\u00edas, querido contribuyente, se acabaron. Y no, no van a volver. Ni rezando.',
      'Desde que la facturaci\u00f3n electr\u00f3nica se volvi\u00f3 obligatoria para pr\u00e1cticamente todos los contribuyentes, la DIAN tiene un ojo digital puesto en cada transacci\u00f3n que haces. \u00bfVendiste un computador? Lo saben. \u00bfCobraste una consultor\u00eda? Lo saben. \u00bfLe vendiste un tinto a tu vecino? Bueno, eso todav\u00eda no... pero dale tiempo.',
      '\u00bfQu\u00e9 es la facturaci\u00f3n electr\u00f3nica?\nEs b\u00e1sicamente una factura normal, pero en formato digital, que se env\u00eda directamente a la DIAN en tiempo real. S\u00ed, EN TIEMPO REAL. Mientras t\u00fa est\u00e1s celebrando esa venta, la DIAN ya est\u00e1 calculando cu\u00e1nto le debes.',
      '\u00bfQui\u00e9nes deben facturar electr\u00f3nicamente?\n\u2022 Responsables del IVA (o sea, casi todo el mundo)\n\u2022 Personas jur\u00eddicas y naturales con ingresos superiores a 3.500 UVT\n\u2022 Comerciantes, prestadores de servicios, importadores\n\u2022 B\u00e1sicamente: si vendes algo y respiras en Colombia, te toca',
      '\u00bfQu\u00e9 pasa si no facturas?\nLa DIAN puede:\n\u2022 Cerrarte el establecimiento (s\u00ed, con candado y todo)\n\u2022 Multarte hasta con 15.000 UVT (eso es mucho dinero para empanaditas)\n\u2022 Inhabilitar tu RUT\n\u2022 Y lo peor: ponerte en la lista de morosos, que es como el Instagram de la gente que le debe a Colombia',
      'Consejo de tu contadora amiga:\nNo esperes a que la DIAN te toque la puerta. Implementa tu facturaci\u00f3n electr\u00f3nica ya. Hay proveedores tecnol\u00f3gicos desde $50.000 al mes. Es menos de lo que gastas en caf\u00e9 a la semana. Y cr\u00e9eme, sale m\u00e1s barato que una multa.',
      'Dato curioso: En 2025, la DIAN report\u00f3 que gracias a la facturaci\u00f3n electr\u00f3nica, el recaudo tributario aument\u00f3 en 23%. O sea, s\u00ed est\u00e1 funcionando. Para ellos, claro. Para tu bolsillo... bueno, eso depende de si tienes un buen contador.',
    ],
    contentEn: [
      'There was a golden era in Colombia where you could sell a million pesos in empanadas, receive cash, and DIAN had no clue. Those days, dear taxpayer, are over. And no, they\'re not coming back. Not even with prayers.',
      'Since electronic invoicing became mandatory for virtually all taxpayers, DIAN has a digital eye on every transaction you make. Sold a computer? They know. Charged for consulting? They know. Sold a coffee to your neighbor? Well, not yet... but give it time.',
      'What is electronic invoicing?\nIt\'s basically a normal invoice, but in digital format, sent directly to DIAN in real time. Yes, IN REAL TIME. While you\'re celebrating that sale, DIAN is already calculating how much you owe them.',
      'Who must invoice electronically?\n\u2022 VAT-responsible parties (so, almost everyone)\n\u2022 Legal entities and individuals with income above 3,500 UVT\n\u2022 Merchants, service providers, importers\n\u2022 Basically: if you sell something and breathe in Colombia, you\'re required to',
      'What happens if you don\'t invoice?\nDIAN can:\n\u2022 Close your establishment (yes, with a padlock and all)\n\u2022 Fine you up to 15,000 UVT (that\'s a lot of money for empanadas)\n\u2022 Disable your RUT\n\u2022 And worst: put you on the debtors list, which is like the Instagram of people who owe Colombia',
      'Advice from your friendly accountant:\nDon\'t wait for DIAN to knock on your door. Implement electronic invoicing now. There are tech providers from $50,000 COP per month. That\'s less than your weekly coffee budget. And trust me, it\'s cheaper than a fine.',
      'Fun fact: In 2025, DIAN reported that thanks to electronic invoicing, tax collection increased by 23%. So yes, it\'s working. For them, of course. For your wallet... well, that depends on whether you have a good accountant.',
    ],
  },
  {
    slug: 'regimen-simple-simple-para-quien',
    title: 'R\u00e9gimen Simple: \u00bfSimple Para Qui\u00e9n? Porque Para M\u00ed No Lo Fue',
    titleEn: 'Simple Tax Regime: Simple For Whom? Because It Wasn\'t For Me',
    excerpt: 'El R\u00e9gimen Simple de Tributaci\u00f3n promete facilitar tu vida fiscal. Pero como todo en la vida, "simple" es relativo. Te explicamos si te conviene o si es mejor salir corriendo.',
    excerptEn: 'The Simple Tax Regime promises to simplify your tax life. But like everything in life, "simple" is relative. We explain if it\'s right for you or if you should run.',
    date: '2026-02-10',
    category: 'Impuestos',
    categoryEn: 'Taxes',
    readTime: 6,
    emoji: '\uD83E\uDD14',
    content: [
      'Cuando el gobierno colombiano anunci\u00f3 el "R\u00e9gimen Simple de Tributaci\u00f3n", muchos emprendedores saltaron de alegr\u00eda. "Por fin algo simple!" dijeron, con la misma inocencia de alguien que cree que armar un mueble de IKEA es f\u00e1cil porque dice "simple" en la caja.',
      'Spoiler alert: no es TAN simple. Pero tampoco es el infierno tributario que ten\u00edamos antes. Es m\u00e1s bien como un purgatorio fiscal. Veamos.',
      '\u00bfQu\u00e9 es el R\u00e9gimen Simple?\nEs un modelo de tributaci\u00f3n que unifica varios impuestos en uno solo:\n\u2022 Impuesto de renta\n\u2022 IVA (en algunos casos)\n\u2022 ICA (Impuesto de Industria y Comercio)\n\u2022 Impuesto al consumo\nTodo se paga en una sola declaraci\u00f3n. Suena bonito, \u00bfverdad?',
      '\u00bfQui\u00e9n puede acogerse?\n\u2022 Personas naturales o jur\u00eddicas\n\u2022 Ingresos brutos iguales o inferiores a 100.000 UVT anuales (aprox. $4.700 millones en 2026)\n\u2022 M\u00e1ximo 50 empleados\n\u2022 No pueden ser sociedades de hecho\n\u2022 No pueden tener deudas con la DIAN (s\u00ed, la DIAN es rencorosa)',
      'Ventajas reales:\n\u2022 Una sola declaraci\u00f3n para varios impuestos\n\u2022 Tarifas progresivas (entre 1.8% y 14.5% seg\u00fan ingresos y actividad)\n\u2022 No se aplica retenci\u00f3n en la fuente (esto es ORO para el flujo de caja)\n\u2022 Puedes descontar aportes al sistema de seguridad social\n\u2022 Anticipos bimestrales: pagas de a poquitos y no te descapitalizas en marzo',
      'Desventajas que nadie te dice:\n\u2022 Si tus proveedores son del r\u00e9gimen ordinario, les complicas la vida con las retenciones\n\u2022 Los anticipos bimestrales igual duelen (no tanto, pero duelen)\n\u2022 Si te pasas de ingresos, te sacan del r\u00e9gimen y te toca volver al ordinario con todas las de la ley\n\u2022 Algunos municipios a\u00fan no tienen convenio para el ICA unificado',
      'Veredicto de tu contadora favorita:\nSi eres un emprendedor o peque\u00f1a empresa con ingresos moderados, el R\u00e9gimen Simple PUEDE ser tu mejor amigo. Pero como todo amigo, hay que conocerlo bien antes de comprometerse. No te inscribas solo porque suena bonito. Haz n\u00fameros primero. O mejor a\u00fan: ll\u00e1mame y los hacemos juntos. Porque para eso estamos.',
    ],
    contentEn: [
      'When the Colombian government announced the "Simple Tax Regime," many entrepreneurs jumped for joy. "Finally something simple!" they said, with the same innocence of someone who thinks assembling IKEA furniture is easy because it says "simple" on the box.',
      'Spoiler alert: it\'s not THAT simple. But it\'s not the tax hellscape we had before either. It\'s more like a fiscal purgatory. Let\'s break it down.',
      'What is the Simple Regime?\nIt\'s a taxation model that unifies several taxes into one:\n\u2022 Income tax\n\u2022 VAT (in some cases)\n\u2022 ICA (Industry and Commerce Tax)\n\u2022 Consumption tax\nEverything is paid in a single declaration. Sounds nice, right?',
      'Who can apply?\n\u2022 Individuals or legal entities\n\u2022 Gross income equal to or less than 100,000 UVT annually (approx. $4.7 billion COP in 2026)\n\u2022 Maximum 50 employees\n\u2022 Cannot be de facto partnerships\n\u2022 Cannot have debts with DIAN (yes, DIAN holds grudges)',
      'Real advantages:\n\u2022 One declaration for multiple taxes\n\u2022 Progressive rates (between 1.8% and 14.5% depending on income and activity)\n\u2022 No withholding tax (this is GOLD for cash flow)\n\u2022 You can deduct social security contributions\n\u2022 Bimonthly advances: pay little by little and don\'t decapitalize in March',
      'Disadvantages nobody tells you:\n\u2022 If your suppliers are in the ordinary regime, you complicate their lives with withholdings\n\u2022 Bimonthly advances still hurt (not as much, but they hurt)\n\u2022 If you exceed income limits, you\'re kicked out and must return to ordinary regime with all its glory\n\u2022 Some municipalities still don\'t have unified ICA agreements',
      'Your favorite accountant\'s verdict:\nIf you\'re an entrepreneur or small business with moderate income, the Simple Regime COULD be your best friend. But like any friend, you need to know them well before committing. Don\'t sign up just because it sounds nice. Do the math first. Or better yet: call me and we\'ll do it together. That\'s what we\'re here for.',
    ],
  },
  {
    slug: 'pecados-contables-empresa',
    title: '7 Pecados Contables Que Tu Empresa Comete (Y Tu Contador Llora en Silencio)',
    titleEn: '7 Accounting Sins Your Business Commits (And Your Accountant Cries Silently)',
    excerpt: 'Mezclar cuentas personales con las de la empresa es solo el comienzo. Aqu\u00ed van los errores que hacen que tu contador considere cambiar de profesi\u00f3n.',
    excerptEn: 'Mixing personal and business accounts is just the beginning. Here are the mistakes that make your accountant consider a career change.',
    date: '2026-02-05',
    category: 'Contabilidad',
    categoryEn: 'Accounting',
    readTime: 7,
    emoji: '\uD83D\uDE31',
    content: [
      'Querido empresario colombiano: te quiero. De verdad. Pero hay cosas que haces que me hacen querer lanzar mi calculadora por la ventana. Y no es una calculadora barata. Hoy vamos a hablar de los 7 pecados contables m\u00e1s comunes. Si te identificas con m\u00e1s de 3... necesitamos hablar.',
      'Pecado #1: Mezclar la plata de la empresa con la personal\n"Pero Andrea, si la empresa soy yo." S\u00ed, pero la DIAN no piensa as\u00ed. Cuando pagas el mercado del hogar con la tarjeta de la empresa, o usas la n\u00f3mina para pagar las vacaciones de la familia, est\u00e1s creando un desastre contable. Abre cuentas separadas. Hoy. Ahora. Ya.',
      'Pecado #2: Guardar facturas en una bolsa pl\u00e1stica del \u00c9xito\nS\u00ed, lo he visto. Clientes que llegan con una bolsa pl\u00e1stica llena de recibos arrugados, manchados de tinto, y me dicen: "Ah\u00ed est\u00e1 toda la contabilidad del a\u00f1o." Eso no es contabilidad. Eso es evidencia de un crimen contra la organizaci\u00f3n.',
      'Pecado #3: No facturar "porque es un cliente de confianza"\nLa confianza no paga impuestos. Si prestas un servicio o vendes un producto, FACTURAS. Punto. Sin factura no hay ingreso registrado, y sin ingreso registrado la DIAN cree que no vendes nada. Y cuando vean que tienes 3 carros y una casa pero "no generas ingresos"... bueno, van a querer conversar.',
      'Pecado #4: Pagar todo en efectivo\nEn Colombia amamos el efectivo. Lo entiendo. Pero cada pago en efectivo que no est\u00e1 soportado es una deducci\u00f3n que pierdes. \u00bfSab\u00edas que puedes deducir gastos de tu renta solo si tienes el soporte de pago? Banco, transferencia, tarjeta. El efectivo sin soporte es como si nunca hubieras gastado... para efectos fiscales.',
      'Pecado #5: Ignorar la n\u00f3mina electr\u00f3nica\n"Pero si solo tengo 2 empleados." No importa. Si tienes empleados, necesitas n\u00f3mina electr\u00f3nica. La DIAN no hace excepciones por tama\u00f1o. Y la multa por no tenerla es bastante m\u00e1s cara que implementarla.',
      'Pecado #6: Declarar a \u00faltima hora\nCada a\u00f1o es la misma historia. Faltan 2 d\u00edas para el vencimiento y ah\u00ed s\u00ed: "Andrea, necesito declarar urgente." Y yo aqu\u00ed, con ojeras, caf\u00e9 por litro, rezando para que los n\u00fameros cuadren. Planifica. Los vencimientos se publican en enero. ENERO.',
      'Pecado #7: Creer que el contador es solo para "la declaraci\u00f3n"\nUn buen contador no es solo quien te llena formularios. Es quien te ahorra dinero, te protege de multas, te asesora en decisiones financieras, y te dice las verdades inc\u00f3modas que nadie m\u00e1s te dice. Usarnos solo en marzo es como tener un m\u00e9dico y solo visitarlo cuando ya est\u00e1s en urgencias.',
      'Si te sentiste identificado con alg\u00fan pecado (o todos), no te preocupes. No es tarde para redimirte. El primer paso es aceptarlo. El segundo es llamar a tu contadora favorita. \u00bfAdivina qui\u00e9n?',
    ],
    contentEn: [
      'Dear Colombian business owner: I love you. Truly. But there are things you do that make me want to throw my calculator out the window. And it\'s not a cheap calculator. Today we\'re talking about the 7 most common accounting sins. If you identify with more than 3... we need to talk.',
      'Sin #1: Mixing business money with personal money\n"But Andrea, the business IS me." Yes, but DIAN doesn\'t think so. When you pay household groceries with the business card, or use payroll to pay for family vacations, you\'re creating an accounting disaster. Open separate accounts. Today. Now. Already.',
      'Sin #2: Keeping invoices in a plastic \u00c9xito bag\nYes, I\'ve seen it. Clients who show up with a plastic bag full of crumpled receipts, stained with coffee, and tell me: "There\'s the whole year\'s accounting." That\'s not accounting. That\'s evidence of a crime against organization.',
      'Sin #3: Not invoicing "because they\'re a trusted client"\nTrust doesn\'t pay taxes. If you provide a service or sell a product, you INVOICE. Period. Without an invoice there\'s no registered income, and without registered income DIAN thinks you sell nothing. And when they see you have 3 cars and a house but "generate no income"... well, they\'ll want to chat.',
      'Sin #4: Paying everything in cash\nIn Colombia we love cash. I get it. But every unsupported cash payment is a deduction you lose. Did you know you can only deduct expenses from your income tax if you have payment proof? Bank, transfer, card. Unsupported cash is as if you never spent it... for tax purposes.',
      'Sin #5: Ignoring electronic payroll\n"But I only have 2 employees." Doesn\'t matter. If you have employees, you need electronic payroll. DIAN makes no exceptions for size. And the fine for not having it is considerably more expensive than implementing it.',
      'Sin #6: Filing at the last minute\nEvery year it\'s the same story. Two days before the deadline: "Andrea, I need to file urgently." And here I am, bags under my eyes, coffee by the liter, praying the numbers add up. Plan ahead. Deadlines are published in January. JANUARY.',
      'Sin #7: Thinking the accountant is only for "the declaration"\nA good accountant isn\'t just someone who fills out forms. They\'re the one who saves you money, protects you from fines, advises on financial decisions, and tells you uncomfortable truths nobody else will. Using us only in March is like having a doctor and only visiting when you\'re already in the ER.',
      'If you identified with any sin (or all of them), don\'t worry. It\'s not too late to redeem yourself. The first step is accepting it. The second is calling your favorite accountant. Guess who?',
    ],
  },
  {
    slug: 'declaracion-renta-historia-de-terror',
    title: 'Tu Declaraci\u00f3n de Renta 2026: Una Historia de Terror Con Final Feliz',
    titleEn: 'Your 2026 Tax Return: A Horror Story With a Happy Ending',
    excerpt: '\u00bfSab\u00edas que si ganas m\u00e1s de $59 millones al a\u00f1o ya debes declarar renta? Respira. No entres en p\u00e1nico. Bueno, un poquito s\u00ed. Pero aqu\u00ed te explicamos todo.',
    excerptEn: 'Did you know that if you earn more than $59 million COP per year you must file a tax return? Breathe. Don\'t panic. Well, a little bit. But we explain everything here.',
    date: '2026-01-28',
    category: 'Renta',
    categoryEn: 'Tax Returns',
    readTime: 8,
    emoji: '\uD83D\uDC7B',
    content: [
      'Es esa \u00e9poca del a\u00f1o otra vez. Ese momento en que la palabra "renta" hace que te suden las manos, se te acelere el coraz\u00f3n, y empieces a buscar desesperadamente ese certificado de retenci\u00f3n que tu empresa te dio en marzo y que "guardaste en un lugar seguro" (traducci\u00f3n: no tienes idea d\u00f3nde est\u00e1).',
      '\u00bfQui\u00e9n debe declarar renta en 2026?\nSi cumples CUALQUIERA de estos requisitos, te toca:\n\u2022 Ingresos brutos superiores a 1.400 UVT (~$66 millones)\n\u2022 Patrimonio bruto superior a 4.500 UVT (~$213 millones)\n\u2022 Consumos con tarjeta de cr\u00e9dito superiores a 1.400 UVT\n\u2022 Compras y consumos totales superiores a 1.400 UVT\n\u2022 Consignaciones bancarias superiores a 1.400 UVT\nS\u00ed, la DIAN tiene muchas formas de atraparte. Es como un pulpo fiscal.',
      '\u00bfQu\u00e9 puedo deducir?\nAqu\u00ed es donde un buen contador vale ORO:\n\u2022 Intereses de cr\u00e9dito de vivienda (hasta 1.200 UVT)\n\u2022 Aportes a pensi\u00f3n obligatoria y voluntaria\n\u2022 Aportes a cuentas AFC\n\u2022 Gastos de salud prepagada\n\u2022 Dependientes econ\u00f3micos (hijos, padres)\n\u2022 El 25% de renta exenta laboral\nCada deducci\u00f3n es plata que NO pagas en impuestos. \u00bfVes por qu\u00e9 es importante tener un contador y no solo Google?',
      'Errores comunes que te cuestan millones:\n\u2022 No incluir TODOS los ingresos (la DIAN cruza informaci\u00f3n, no seas ingenuo)\n\u2022 No solicitar certificados de retenci\u00f3n a tiempo\n\u2022 Olvidar incluir cuentas bancarias en el exterior (s\u00ed, eso de Nequi no es "exterior", pero las de PayPal s\u00ed cuentan)\n\u2022 Declarar despu\u00e9s de la fecha l\u00edmite (la sanci\u00f3n por extempor\u00e1nea duele)',
      'Calendario tributario 2026:\nLas fechas de vencimiento dependen de los dos \u00faltimos d\u00edgitos de tu NIT/c\u00e9dula. Generalmente van de agosto a octubre. Pero NO esperes a agosto para empezar a organizar tu informaci\u00f3n. Empieza AHORA. En serio. Ahora.',
      '\u00bfCu\u00e1nto voy a pagar?\nDepende de tu renta l\u00edquida gravable. Las tarifas para personas naturales en 2026 van de 0% a 39%. S\u00ed, 39%. Pero antes de que te d\u00e9 un infarto: las deducciones y exenciones pueden reducir significativamente esa base. Por eso insisto: CONTADOR. PROFESIONAL. YA.',
      'Final feliz:\nCon la planeaci\u00f3n adecuada, tu declaraci\u00f3n de renta no tiene que ser una pesadilla. Puede ser un tr\u00e1mite ordenado, optimizado, y hasta puedes terminar con un saldo a favor. S\u00ed, la DIAN a veces te debe plata a TI. Es raro, pero pasa. Y cuando pasa, se siente como ganarse la loter\u00eda fiscal.',
    ],
    contentEn: [
      'It\'s that time of year again. That moment when the word "tax return" makes your palms sweat, your heart race, and you desperately search for that withholding certificate your company gave you in March that you "put in a safe place" (translation: you have no idea where it is).',
      'Who must file a tax return in 2026?\nIf you meet ANY of these requirements, you\'re in:\n\u2022 Gross income over 1,400 UVT (~$66 million COP)\n\u2022 Gross assets over 4,500 UVT (~$213 million COP)\n\u2022 Credit card spending over 1,400 UVT\n\u2022 Total purchases and consumption over 1,400 UVT\n\u2022 Bank deposits over 1,400 UVT\nYes, DIAN has many ways to catch you. It\'s like a fiscal octopus.',
      'What can I deduct?\nThis is where a good accountant is worth GOLD:\n\u2022 Mortgage interest (up to 1,200 UVT)\n\u2022 Mandatory and voluntary pension contributions\n\u2022 AFC savings account contributions\n\u2022 Prepaid health expenses\n\u2022 Economic dependents (children, parents)\n\u2022 The 25% exempt employment income\nEvery deduction is money you DON\'T pay in taxes. See why it\'s important to have an accountant and not just Google?',
      'Common mistakes that cost you millions:\n\u2022 Not including ALL income (DIAN cross-references information, don\'t be naive)\n\u2022 Not requesting withholding certificates on time\n\u2022 Forgetting to include foreign bank accounts (yes, Nequi isn\'t "foreign," but PayPal accounts count)\n\u2022 Filing after the deadline (the late penalty hurts)',
      'Tax calendar 2026:\nDeadline dates depend on the last two digits of your NIT/ID number. They generally run from August to October. But DON\'T wait until August to start organizing your information. Start NOW. Seriously. Now.',
      'How much will I pay?\nIt depends on your taxable net income. Rates for individuals in 2026 range from 0% to 39%. Yes, 39%. But before you have a heart attack: deductions and exemptions can significantly reduce that base. That\'s why I insist: ACCOUNTANT. PROFESSIONAL. NOW.',
      'Happy ending:\nWith proper planning, your tax return doesn\'t have to be a nightmare. It can be an organized, optimized process, and you might even end up with a balance in your favor. Yes, DIAN sometimes owes money to YOU. It\'s rare, but it happens. And when it does, it feels like winning the fiscal lottery.',
    ],
  },
  {
    slug: 'sagrilaft-tienda-empanadas',
    title: 'SAGRILAFT: Porque Hasta Tu Tienda de Empanadas Necesita Prevenir Lavado de Activos',
    titleEn: 'SAGRILAFT: Because Even Your Empanada Shop Needs to Prevent Money Laundering',
    excerpt: 'No, SAGRILAFT no es una enfermedad. Es el sistema que tu empresa necesita para demostrar que no est\u00e1s lavando dinero. Y s\u00ed, aplica para m\u00e1s empresas de las que crees.',
    excerptEn: 'No, SAGRILAFT isn\'t a disease. It\'s the system your business needs to prove you\'re not laundering money. And yes, it applies to more businesses than you think.',
    date: '2026-01-20',
    category: 'Cumplimiento',
    categoryEn: 'Compliance',
    readTime: 6,
    emoji: '\uD83E\uDDFD',
    content: [
      'La primera vez que un cliente me dijo: "\u00bfSAGRI-QU\u00c9?", supe que ten\u00eda que escribir este art\u00edculo. Porque si t\u00fa tambi\u00e9n frunciste el ce\u00f1o al leer "SAGRILAFT", tranquilo. No est\u00e1s solo. Pero despu\u00e9s de hoy, vas a saber exactamente qu\u00e9 es y por qu\u00e9 te importa.',
      '\u00bfQu\u00e9 diablos es SAGRILAFT?\nSon las siglas de: Sistema de Autogesti\u00f3n del Riesgo Integral de Lavado de Activos, Financiaci\u00f3n del Terrorismo y Financiamiento de la Proliferaci\u00f3n de Armas de Destrucci\u00f3n Masiva.\n\nS\u00ed, es un nombre largo. Tan largo como la multa que te ponen si no lo implementas.',
      '\u00bfQui\u00e9n necesita SAGRILAFT?\nLa Supersociedades lo exige para empresas que:\n\u2022 Tengan ingresos totales iguales o superiores a 30.000 SMMLV\n\u2022 O activos totales iguales o superiores a 30.000 SMMLV\n\nPara 2026, eso es aproximadamente $39.000 millones. "Ah, entonces mi empresita no aplica." Espera. Tambi\u00e9n existe el PADM (Programa de Autocontrol y Gesti\u00f3n del Riesgo), que aplica para empresas m\u00e1s peque\u00f1as. Sorpresa.',
      '\u00bfQu\u00e9 implica tener un SAGRILAFT?\n\u2022 Nombrar un Oficial de Cumplimiento (alguien que sepa lo que hace, no tu primo)\n\u2022 Tener pol\u00edticas escritas de prevenci\u00f3n de lavado de activos\n\u2022 Conocer a tus clientes y proveedores (KYC - Know Your Customer)\n\u2022 Reportar operaciones sospechosas a la UIAF\n\u2022 Capacitar a tu personal\n\u2022 Hacer seguimiento y auditor\u00edas peri\u00f3dicas',
      '\u00bfQu\u00e9 pasa si no lo tengo?\n\u2022 Multas de hasta 200 SMMLV (eso son m\u00e1s de $260 millones)\n\u2022 Sanciones administrativas de la Supersociedades\n\u2022 Da\u00f1o reputacional (nadie quiere hacer negocios con una empresa investigada)\n\u2022 Y en el peor caso: investigaciones penales\n\nNo es broma. El lavado de activos es un delito serio y las autoridades colombianas est\u00e1n cada vez m\u00e1s estrictas.',
      'Pero Andrea, mi empresa es leg\u00edtima...\nLo s\u00e9. Y por eso mismo necesitas SAGRILAFT. No es para empresas que lavan dinero. Es para empresas que quieren DEMOSTRAR que no lo hacen. Es tu escudo legal. Tu certificado de "soy limpio y puedo probarlo."',
      'Mi consejo:\nNo esperes a que la Supersociedades te env\u00ede una carta bonita. Implementa tu SAGRILAFT o PADM proactivamente. Es una inversi\u00f3n en la reputaci\u00f3n y seguridad jur\u00eddica de tu empresa. Y s\u00ed, yo te puedo ayudar. Es literalmente mi especialidad. Llama antes de que sea tarde.',
    ],
    contentEn: [
      'The first time a client told me: "SAGRI-WHAT?", I knew I had to write this article. Because if you also frowned when reading "SAGRILAFT," relax. You\'re not alone. But after today, you\'ll know exactly what it is and why it matters.',
      'What the heck is SAGRILAFT?\nIt stands for: Self-Management System for Comprehensive Risk of Money Laundering, Terrorism Financing, and Financing of Weapons of Mass Destruction Proliferation.\n\nYes, it\'s a long name. Almost as long as the fine they give you for not implementing it.',
      'Who needs SAGRILAFT?\nThe Superintendencia de Sociedades requires it for companies that:\n\u2022 Have total income equal to or above 30,000 minimum wages\n\u2022 Or total assets equal to or above 30,000 minimum wages\n\nFor 2026, that\'s approximately $39 billion COP. "Oh, then my little company doesn\'t qualify." Wait. There\'s also PADM (Risk Self-Control and Management Program), which applies to smaller companies. Surprise.',
      'What does having SAGRILAFT entail?\n\u2022 Appoint a Compliance Officer (someone who knows what they\'re doing, not your cousin)\n\u2022 Have written anti-money laundering policies\n\u2022 Know your clients and suppliers (KYC - Know Your Customer)\n\u2022 Report suspicious operations to UIAF\n\u2022 Train your staff\n\u2022 Conduct periodic monitoring and audits',
      'What happens if I don\'t have it?\n\u2022 Fines of up to 200 minimum wages (that\'s over $260 million COP)\n\u2022 Administrative sanctions from the Superintendencia\n\u2022 Reputational damage (nobody wants to do business with an investigated company)\n\u2022 And in the worst case: criminal investigations\n\nThis is not a joke. Money laundering is a serious crime and Colombian authorities are increasingly strict.',
      'But Andrea, my company is legitimate...\nI know. And that\'s precisely why you need SAGRILAFT. It\'s not for companies that launder money. It\'s for companies that want to PROVE they don\'t. It\'s your legal shield. Your certificate of "I\'m clean and I can prove it."',
      'My advice:\nDon\'t wait for the Superintendencia to send you a nice letter. Implement your SAGRILAFT or PADM proactively. It\'s an investment in your company\'s reputation and legal security. And yes, I can help. It\'s literally my specialty. Call before it\'s too late.',
    ],
  },
  {
    slug: 'uvt-2026-numerito-controla-vida',
    title: 'El UVT 2026: El Numerito Que Controla Tu Vida Fiscal (Y Ni Lo Sab\u00edas)',
    titleEn: 'UVT 2026: The Little Number That Controls Your Tax Life (And You Didn\'t Even Know)',
    excerpt: 'Cada a\u00f1o sube la UVT y cada a\u00f1o t\u00fa pagas m\u00e1s impuestos sin darte cuenta. Te explicamos qu\u00e9 es, cu\u00e1nto vale, y por qu\u00e9 deber\u00eda importarte m\u00e1s que el precio del d\u00f3lar.',
    excerptEn: 'Every year the UVT goes up and every year you pay more taxes without realizing it. We explain what it is, how much it\'s worth, and why it should matter more to you than the dollar exchange rate.',
    date: '2026-01-12',
    category: 'Impuestos',
    categoryEn: 'Taxes',
    readTime: 5,
    emoji: '\uD83D\uDCCA',
    content: [
      'Hay un n\u00famerito en Colombia que sube cada a\u00f1o, que define cu\u00e1nto pagas en impuestos, cu\u00e1nto te multan, y hasta si debes o no declarar renta. Y la mayor\u00eda de colombianos no tiene idea de que existe. Se llama UVT: Unidad de Valor Tributario. Y hoy vas a aprender a respetarla.',
      '\u00bfQu\u00e9 es la UVT?\nEs una unidad de medida que usa la DIAN para calcular TODO en el mundo tributario colombiano. En vez de poner valores fijos en pesos (que se desactualizan con la inflaci\u00f3n), el gobierno usa UVTs. As\u00ed, cada a\u00f1o solo actualizan el valor de 1 UVT y autom\u00e1ticamente se actualizan todos los topes, multas, y tarifas.',
      'Valor de la UVT en 2026: $47.065 (aproximado)\n\nPara que tengas referencia:\n\u2022 2023: $42.412\n\u2022 2024: $44.007\n\u2022 2025: $45.547\n\u2022 2026: $47.065\n\n\u00bfVes c\u00f3mo sube? Cada a\u00f1o m\u00e1s. Como el arriendo, pero menos divertido.',
      '\u00bfD\u00f3nde aparece la UVT en tu vida?\n\u2022 Declaraci\u00f3n de renta: Debes declarar si tus ingresos superan 1.400 UVT (~$66 millones)\n\u2022 Sanci\u00f3n m\u00ednima: 10 UVT (~$470.000). S\u00ed, la multa m\u00e1s peque\u00f1a que te puede poner la DIAN\n\u2022 Facturaci\u00f3n electr\u00f3nica: Obligatoria si superas 3.500 UVT en ingresos\n\u2022 Retenci\u00f3n en la fuente: Los topes de retenci\u00f3n se calculan en UVTs\n\u2022 Beneficios tributarios: Los l\u00edmites de deducciones est\u00e1n en UVTs',
      'El truco que nadie te dice:\nComo la UVT sube cada a\u00f1o con la inflaci\u00f3n, los topes en pesos tambi\u00e9n suben. Esto significa que, aunque el tope para declarar renta "parece" m\u00e1s alto cada a\u00f1o, en realidad es casi lo mismo en t\u00e9rminos reales. La DIAN no te est\u00e1 dando un respiro. Est\u00e1 ajustando por inflaci\u00f3n. Diferente.',
      'Lo que SÍ cambia:\nCuando la UVT sube, las MULTAS tambi\u00e9n suben en pesos. Eso s\u00ed lo sientes. Esa sanci\u00f3n de 10 UVT que en 2023 eran $424.000, en 2026 son $470.000. No es mucha diferencia, pero imagina multas de 1.000 UVT o m\u00e1s. Ah\u00ed s\u00ed duele.',
      'Consejo final:\nMant\u00e9n la UVT actualizada en tu cabeza. O mejor a\u00fan, mant\u00e9n a tu contadora actualizada en tu tel\u00e9fono. Porque cada vez que el gobierno publica la nueva UVT, cambian los n\u00fameros que afectan tu bolsillo. Y es mejor enterarse por tu contadora que por una notificaci\u00f3n de la DIAN.',
    ],
    contentEn: [
      'There\'s a little number in Colombia that goes up every year, defines how much you pay in taxes, how much they fine you, and even whether you must file a tax return. And most Colombians have no idea it exists. It\'s called UVT: Tax Value Unit. And today you\'re going to learn to respect it.',
      'What is the UVT?\nIt\'s a unit of measurement that DIAN uses to calculate EVERYTHING in Colombia\'s tax world. Instead of setting fixed values in pesos (which become outdated with inflation), the government uses UVTs. This way, each year they only update the value of 1 UVT and automatically all thresholds, fines, and rates are updated.',
      'UVT value in 2026: $47,065 COP (approximate)\n\nFor reference:\n\u2022 2023: $42,412\n\u2022 2024: $44,007\n\u2022 2025: $45,547\n\u2022 2026: $47,065\n\nSee how it goes up? Every year more. Like rent, but less fun.',
      'Where does the UVT appear in your life?\n\u2022 Tax return: You must file if your income exceeds 1,400 UVT (~$66 million COP)\n\u2022 Minimum penalty: 10 UVT (~$470,000). Yes, the smallest fine DIAN can give you\n\u2022 Electronic invoicing: Mandatory if you exceed 3,500 UVT in income\n\u2022 Withholding tax: Withholding thresholds are calculated in UVTs\n\u2022 Tax benefits: Deduction limits are in UVTs',
      'The trick nobody tells you:\nSince the UVT rises each year with inflation, the thresholds in pesos also rise. This means that although the threshold for filing a tax return "seems" higher each year, it\'s actually almost the same in real terms. DIAN isn\'t giving you a break. They\'re adjusting for inflation. Different.',
      'What DOES change:\nWhen the UVT goes up, FINES also go up in pesos. You feel that. That 10 UVT penalty that was $424,000 in 2023 is $470,000 in 2026. Not a huge difference, but imagine fines of 1,000 UVT or more. That\'s where it hurts.',
      'Final advice:\nKeep the UVT updated in your head. Or better yet, keep your accountant updated in your phone. Because every time the government publishes the new UVT, the numbers affecting your wallet change. And it\'s better to find out from your accountant than from a DIAN notification.',
    ],
  },
];

export function getPostBySlug(slug: string): BlogPost | undefined {
  return posts.find((p) => p.slug === slug);
}
